= initializr-cli

Experimental `CLI` for https://github.com/spring-io/initializr[initializr] implemented with https://github.com/spring-projects/spring-shell[spring-shell] defaulting to https://start.spring.io[start.spring.io]. Focus of this `CLI` is to make it more user friendly to create a project from a command line and also demonstrate _native_ capabilities with https://github.com/spring-projects-experimental/spring-native[spring-native].

== Build

NOTE: Use either JDK11 or JDK17

Normal build without _native_:
```
./gradlew clean build -x test
```

Which you can then run with:
```
java -jar build/libs/initializr-cli-0.0.1-SNAPSHOT.jar
```

For native build:
```
./gradlew clean build nativeCompile
```

NOTE: You need to have `GRAALVM_HOME` pointing to your _graal_ installation

Which you can then run with:
```
./build/native/nativeCompile/initializr-cli
```

== Docs

=== Generic Commands

```
initializr:>help
AVAILABLE COMMANDS

Built-In Commands
        completion bash: Generate bash completion script
        help: Display help about available commands.
        history: Display or save the history of previously run commands
        script: Read and execute commands from a file.
        version: Show version info

Initializr Commands
        dependencies: List supported dependencies
        info: Show the Initializr server being used
        init: Initialize project
```

=== Listing dependencies

```
NAME
	dependencies - List supported dependencies

SYNOPSYS
	dependencies [[--search] string]  [[--version] string]

OPTIONS
	--search  string
		Search string to limit results
		[Optional, default = <none>]

	--version  string
		Limit to compatibility version
		[Optional, default = <none>]
```

=== Generating a project

```
initializr:>help init


NAME
	init - Initialize project

SYNOPSYS
	init [--path] string  [[--project] string]  [[--language] string]  [[--boot-version] string]  [[--version] string]  [[--group] string]  [[--artifact] string]  [[--name] string]  [[--description] string]  [[--package-name] string]  [[--dependencies] list]  [[--packaging] string]  [[--java-version] string]

OPTIONS
	--path  string
		Path to extract
		[Mandatory]

	--project  string
		Project
		[Optional, default = <none>]

	--language  string
		Language
		[Optional, default = <none>]

	--boot-version  string
		Language
		[Optional, default = <none>]

	--version  string
		Version
		[Optional, default = <none>]

	--group  string
		Group
		[Optional, default = <none>]

	--artifact  string
		Artifact
		[Optional, default = <none>]

	--name  string
		Name
		[Optional, default = <none>]

	--description  string
		Description
		[Optional, default = <none>]

	--package-name  string
		Package Name
		[Optional, default = <none>]

	--dependencies  list
		Dependencies
		[Optional, default = <none>]

	--packaging  string
		Packaging
		[Optional, default = <none>]

	--java-version  string
		Java
		[Optional, default = <none>]

```

=== Non-Interactive Mode

Currently if you pass any parameters into a shell from startup it enters into non-interactive mode.

With native:

```
./build/native/nativeCompile/initializr-cli help
Built-In Commands
        completion bash: Generate bash completion script
        help: Display help about available commands.
        history: Display or save the history of previously run commands
        script: Read and execute commands from a file.
        version: Show version info

Initializr Commands
        dependencies: List supported dependencies
        info: Show the Initializr server being used
        init: Initialize project
```

With jar:

```
$ java -jar build/libs/initializr-cli-0.0.1-SNAPSHOT.jar help
AVAILABLE COMMANDS

Built-In Commands
        completion bash: Generate bash completion script
        help: Display help about available commands.
        history: Display or save the history of previously run commands
        script: Read and execute commands from a file.
        version: Show version info

Initializr Commands
        dependencies: List supported dependencies
        info: Show the Initializr server being used
        init: Initialize project
```

=== Shell Completion

Shell completion for `bash` can be generate with `completion bash` command:

```
$ source <(initializr-cli completion bash)
```

== Demos

Generate project:

image::https://asciinema.org/a/JYxbnmbvEJTF1sFA3o5FGVCJW.svg[asciicast,link="https://asciinema.org/a/JYxbnmbvEJTF1sFA3o5FGVCJW"]

List dependencies from a server:

image::https://asciinema.org/a/g85jSakIuz3bz9uQcUKNCkA3T.svg[asciicast,link="https://asciinema.org/a/g85jSakIuz3bz9uQcUKNCkA3T"]
