spring:
  main:
    web-application-type: none
## disable console logging
logging:
 pattern:
   console:
## log debug from a cli
#  file:
#    name: shell.log
#  level:
#    org.springframework.experimental.initializrcli: debug
