spring:
  main:
    web-application-type: none
    banner-mode: off
  shell:
    command:
      completion:
        root-command: initializr-cli
      version:
        show-git-short-commit-id: true

## disable console logging
logging:
  pattern:
    console:
## log debug from a cli
  file:
    name: shell.log
  level:
    # root: debug
    org:
      springframework:
        experimental:
          initializrcli: debug
        shell: debug
