name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       java: [ '11', '17' ]
  #   name: CI Build ${{ matrix.java }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-java@v2
  #       with:
  #         distribution: adopt
  #         java-version: ${{ matrix.java }}
  #         cache: gradle
  #     - run: ./gradlew build --no-daemon
  native:
    # needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ['22.0.0.2']
        os: [windows-latest]
    name: CI Native ${{ matrix.version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.version }}
          java-version: 11
          components: native-image
          set-java-home: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Native Compile (windows)
        run: |
          ./gradlew build nativeCompile --no-daemon
        if: runner.os == 'Windows'
      - uses: actions/upload-artifact@v2
        with:
          name: initializr-cli-${{ matrix.os }}-${{ matrix.version }}
          path: build/native/nativeCompile/
          retention-days: 1
      - name: Run Commands (linux/macos)
        run: |
          build/native/nativeCompile/initializr-cli version
        if: runner.os != 'Windows'
      - name: Run Commands (windows)
        run: |
          Get-ChildItem env:
          build/native/nativeCompile/initializr-cli.exe version
          cat shell.log
        if: runner.os == 'Windows'
